# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:/FatherProject/ui\group.ui'
#
# Created: Wed Feb 10 07:53:06 2021
#      by: pyside2-uic  running on PySide2 2.0.0~alpha0
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_Group(object):
    def setupUi(self, Group):
        Group.setObjectName("Group")
        Group.resize(550, 301)
        Group.setStyleSheet("")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Group)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Mail_Group = QtWidgets.QGroupBox(Group)
        self.Mail_Group.setFlat(False)
        self.Mail_Group.setCheckable(True)
        self.Mail_Group.setChecked(True)
        self.Mail_Group.setObjectName("Mail_Group")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.Mail_Group)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.Mail_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.Interval_Combo = QtWidgets.QComboBox(self.Mail_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Interval_Combo.sizePolicy().hasHeightForWidth())
        self.Interval_Combo.setSizePolicy(sizePolicy)
        self.Interval_Combo.setObjectName("Interval_Combo")
        self.Interval_Combo.addItem("")
        self.horizontalLayout_3.addWidget(self.Interval_Combo)
        self.label_2 = QtWidgets.QLabel(self.Mail_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.Send_Time = QtWidgets.QTimeEdit(self.Mail_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Send_Time.sizePolicy().hasHeightForWidth())
        self.Send_Time.setSizePolicy(sizePolicy)
        self.Send_Time.setCurrentSection(QtWidgets.QDateTimeEdit.HourSection)
        self.Send_Time.setObjectName("Send_Time")
        self.horizontalLayout_3.addWidget(self.Send_Time)
        self.Del_BTN = QtWidgets.QPushButton(self.Mail_Group)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Del_BTN.sizePolicy().hasHeightForWidth())
        self.Del_BTN.setSizePolicy(sizePolicy)
        self.Del_BTN.setMaximumSize(QtCore.QSize(24, 24))
        self.Del_BTN.setStyleSheet("background:red")
        self.Del_BTN.setObjectName("Del_BTN")
        self.horizontalLayout_3.addWidget(self.Del_BTN)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.Title_LE = QtWidgets.QLineEdit(self.Mail_Group)
        self.Title_LE.setObjectName("Title_LE")
        self.verticalLayout_4.addWidget(self.Title_LE)
        self.Content_TE = QtWidgets.QTextEdit(self.Mail_Group)
        self.Content_TE.setObjectName("Content_TE")
        self.verticalLayout_4.addWidget(self.Content_TE)
        self.verticalLayout.addLayout(self.verticalLayout_4)
        self.Item_Container = QtWidgets.QFrame(self.Mail_Group)
        self.Item_Container.setFrameShape(QtWidgets.QFrame.Box)
        self.Item_Container.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Item_Container.setLineWidth(2)
        self.Item_Container.setObjectName("Item_Container")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.Item_Container)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Add_BTN = QtWidgets.QPushButton(self.Item_Container)
        self.Add_BTN.setObjectName("Add_BTN")
        self.horizontalLayout_2.addWidget(self.Add_BTN)
        self.Inspect_BTN = QtWidgets.QPushButton(self.Item_Container)
        self.Inspect_BTN.setObjectName("Inspect_BTN")
        self.horizontalLayout_2.addWidget(self.Inspect_BTN)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addWidget(self.Item_Container)
        self.verticalLayout_2.addWidget(self.Mail_Group)

        self.retranslateUi(Group)
        QtCore.QMetaObject.connectSlotsByName(Group)

    def retranslateUi(self, Group):
        Group.setWindowTitle(QtWidgets.QApplication.translate("Group", "Form", None, -1))
        self.Mail_Group.setTitle(QtWidgets.QApplication.translate("Group", "邮件组", None, -1))
        self.label_5.setText(QtWidgets.QApplication.translate("Group", "发送间隔", None, -1))
        self.Interval_Combo.setItemText(0, QtWidgets.QApplication.translate("Group", "每天", None, -1))
        self.label_2.setText(QtWidgets.QApplication.translate("Group", "发送时间", None, -1))
        self.Send_Time.setDisplayFormat(QtWidgets.QApplication.translate("Group", "HH:mm", None, -1))
        self.Del_BTN.setText(QtWidgets.QApplication.translate("Group", "X", None, -1))
        self.Title_LE.setPlaceholderText(QtWidgets.QApplication.translate("Group", "邮件标题...", None, -1))
        self.Content_TE.setPlaceholderText(QtWidgets.QApplication.translate("Group", "邮件正文内容...", None, -1))
        self.Add_BTN.setText(QtWidgets.QApplication.translate("Group", "添加抓取数据", None, -1))
        self.Inspect_BTN.setText(QtWidgets.QApplication.translate("Group", "数据校验", None, -1))

